### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by manuel-quezada** [ketch/shallow_water_periodic_bathymetry#15]
- [x] Get new 3D NS simulation (with variance=4).
- [x] Update the 2D NS simulations that serve as reference for the 3D results.  
- [x] Depending on the results, reformulate the statements about the simulation being under resolved and how well split and formed are the solitary waves. 
- [x] Mention the number of DOFs and update the cost of the 3D-NS simulation. 
- [x] Make a cover letter.
- [x] Update repository about reproducibility.
