### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ketch** [ketch/shallow_water_periodic_bathymetry#3]
Several modifications that I think we should make are:

- [x] Possibly cite recent related work (for linear waves) by Ockendon
- [x] Make Figure 1 clearer, possibly with an isometric view
- [x] Redo Figure 2 to properly show the relevant scales including epsilon, Omega, lambda, and L
- [x] Redo legend in Figure 3 to refer to the models rather than the numerical methods.  Just use one legend for the 3 figures.  Possibly switch to waterfall plots.
- [x] Perhaps show SW (and KdV?) solutions for the setting mentioned at the end of section 4.1.
- [x] Indicate relevant points (corresponding to our experiments) in Figure 8.
- [x] Fix the caption of Figures 9-11
- [x] In Figures 10-11, perhaps use fewer and larger plots.
- [x] Perhaps move Figure 12 earlier in the paper.

Notation and terminology:

- Perhaps switch to writing b_1, b_2
- Use terms "bathymetric dispersion" and "KdV dispersion"

**Comment by manuel-quezada** [comment]
I will deal with this issue via PR #5

**Comment by manuel-quezada** [comment]
As far as I can say, there are mainly two papers by Ockendon that deal with this type of problem. One is related to Z-dispersion and the other one to C-dispersion. Since we are not citing all the work that deals with Z-dispersion but only the work by Santosa, I suggest we only cite the paper by Ockendon related to C-dispersion. This makes sense to me since our paper is mainly relaterd to this type of dispersion.

**Comment by manuel-quezada** [comment]
About figure 2, I did some changes to include epsilon and lambda. As for Omega and L, these quantities are shown in figure 1. I think I prefer to keep figure 2 not too dense.

**Comment by manuel-quezada** [comment]
I don't think it is possible to indicate the relevant points corresponding to our experiments in Figure 8. The reason is that such plots depend on the value of eta_0 and we are changing that value between the different experiments. I included two sentences indicating the ratio of the coefficients for the two cases of interest: 1) when the KdV-like dispersion is stronger and 2) when the bathymetric dispersion is stronger.

**Comment by manuel-quezada** [comment]
About Figure 12, I suppose you meant to maybe move it closer to Figure 7. Is that right? If that is the case, I am not sure I agree. The reason being that at that point we haven't talked about the NS equations and it might not make sense to introduce these results yet. I added a sentence right after presenting figures 7a-7c where I indicate that the same situation is simulated via the incompressible NS equations in the following section.

**Comment by manuel-quezada** [comment]
- I made the macro \ST for \sigma^{\scriptsize \text{ST}} which I am using to denote the coefficient for the surface tension. 

- I made the macros \bA and \bB in case we want to use b_1 and b_2 instead.

**Comment by ketch** [comment]
>As far as I can say, there are mainly two papers by Ockendon that deal with this type of problem. One is related to Z-dispersion and the other one to C-dispersion. Since we are not citing all the work that deals with Z-dispersion but only the work by Santosa, I suggest we only cite the paper by Ockendon related to C-dispersion. This makes sense to me since our paper is mainly relaterd to this type of dispersion.

That sounds good.

**Comment by manuel-quezada** [comment]
I changed the legend in figure 3, fix the captions of figures 9-11, changed figure 10 and 11 with new results and move figure 12 as we discussed. All these (and other) changes are in PR #6.
